// Write a loop to print  " I am sorry baby "  100 times.

void main() {
  int i = 0;
  while (i <= 100) {
    print("I am sorry baby.");
    i++;
  }
}
/*[output]
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby.
I am sorry baby. */
